-- HirayaCareers
-- SQL script for inserting sample data
-- Run this script after CreateDatabase.sql.

-- Sample users
-- The PasswordHash values are placeholders for database demonstration.
-- Replace them with hashes generated by the application if sample
-- accounts need to be used for login.

INSERT INTO dbo.Users
    (FirstName, LastName, Email, PasswordHash, Role, CreatedAt)
VALUES
    ('Emma', 'Wilson', 'emma.wilson@sample.com',
     'SAMPLE_HASH_EMPLOYER_1', 'Employer', SYSDATETIME()),

    ('Liam', 'Brown', 'liam.brown@sample.com',
     'SAMPLE_HASH_EMPLOYER_2', 'Employer', SYSDATETIME()),

    ('Sophie', 'Taylor', 'sophie.taylor@sample.com',
     'SAMPLE_HASH_JOBSEEKER_1', 'JobSeeker', SYSDATETIME()),

    ('Noah', 'Martin', 'noah.martin@sample.com',
     'SAMPLE_HASH_JOBSEEKER_2', 'JobSeeker', SYSDATETIME());

INSERT INTO dbo.Jobs
    (Title, CompanyName, Location, EmploymentType,
     Description, Requirements, DatePosted, EmployerId)
VALUES
    (
        'Junior Software Developer',
        'Nova Digital Ltd',
        'Auckland',
        'Full-time',
        'Support the development and maintenance of web applications.',
        'Basic knowledge of C#, ASP.NET Core, SQL, Git, and web development.',
        SYSDATETIME(),
        (SELECT UserId FROM dbo.Users
         WHERE Email = 'emma.wilson@sample.com')
    ),
    (
        'IT Support Technician',
        'Harbour Technology Services',
        'Auckland',
        'Part-time',
        'Provide first-level technical support for users and business systems.',
        'Knowledge of Windows, networking, troubleshooting, and customer service.',
        SYSDATETIME(),
        (SELECT UserId FROM dbo.Users
         WHERE Email = 'liam.brown@sample.com')
    ),
    (
        'Web Designer',
        'Creative Kiwi Studio',
        'Wellington',
        'Contract',
        'Design responsive and user-friendly websites for business clients.',
        'Experience with HTML, CSS, JavaScript, and responsive design.',
        SYSDATETIME(),
        (SELECT UserId FROM dbo.Users
         WHERE Email = 'emma.wilson@sample.com')
    );

INSERT INTO dbo.JobApplications
    (JobId, UserId, CoverLetter, Status, AppliedAt, ResumePath)
VALUES
    (
        (SELECT TOP 1 JobId
         FROM dbo.Jobs
         WHERE Title = 'Junior Software Developer'
         ORDER BY JobId),
        (SELECT UserId
         FROM dbo.Users
         WHERE Email = 'sophie.taylor@sample.com'),
        'I am interested in the Junior Software Developer position and would welcome the opportunity to contribute my technical skills.',
        'Pending',
        SYSDATETIME(),
        NULL
    ),
    (
        (SELECT TOP 1 JobId
         FROM dbo.Jobs
         WHERE Title = 'IT Support Technician'
         ORDER BY JobId),
        (SELECT UserId
         FROM dbo.Users
         WHERE Email = 'noah.martin@sample.com'),
        'I am applying for the IT Support Technician role because my technical support experience matches the position requirements.',
        'Accepted',
        SYSDATETIME(),
        NULL
    );